# Generated by Django 5.2.3 on 2025-07-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_venda_produtos_itensdopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensdopedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itensdopedido',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='ItensDoPedido',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
