# Generated by Django 5.2.3 on 2025-08-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_itensdopedido_produto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar clientes'),)},
        ),
    ]
